In [1]:
# Install the packages we need

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# 1.	Load the NBA data

In [2]:
# Load the data

NBA19 = pd.read_excel("Assignment Data/NBA2019odds.xlsx")
NBA19

team               opponent  day  month  year  winodds  \
0     Golden State Warriors        Houston Rockets    4      1  2019     1.27   
1           Houston Rockets  Golden State Warriors    4      1  2019     3.92   
2           New York Knicks     Washington Wizards   17      1  2019     3.52   
3        Washington Wizards        New York Knicks   17      1  2019     1.32   
4            Boston Celtics     Los Angeles Lakers    8      2  2019     1.24   
...                     ...                    ...  ...    ...   ...      ...   
2455  Golden State Warriors      Charlotte Hornets    1      4  2019     1.13   
2456       Dallas Mavericks              Utah Jazz   15     11  2018     2.75   
2457              Utah Jazz       Dallas Mavericks   15     11  2018     1.47   
2458         Boston Celtics          Chicago Bulls    9     12  2018     1.28   
2459          Chicago Bulls         Boston Celtics    9     12  2018     3.80   

      loseodds  teampts  oppopts  diff  overtime  home  \
0         3.92      134      135     1         1     1   
1         1.27      135      134     1         1     0   
2         1.32      100      101     1         0     0   
3         3.52      101      100     1         0     1   
4         4.31      128      129     1         0     1   
...        ...      ...      ...   ...       ...   ...   
2455      6.42      137       90    47         0     1   
2456      1.47      118       68    50         0     1   
2457      2.75       68      118    50         0     0   
2458      3.80      133       77    56         0     0   
2459      1.28       77      133    56         0     1   

                                Game(home-away)     HAscore  win prob  win  
0       Golden State Warriors - Houston Rockets  134:135 ET  0.755299    0  
1       Golden State Warriors - Houston Rockets  134:135 ET  0.244701    1  
2          Washington Wizards - New York Knicks     101:100  0.272727    0  
3          Washington Wizards - New York Knicks     101:100  0.727273    1  
4           Boston Celtics - Los Angeles Lakers     128:129  0.776577    0  
...                                         ...         ...       ...  ...  
2455  Golden State Warriors - Charlotte Hornets      137:90  0.850331    1  
2456               Dallas Mavericks - Utah Jazz      118:68  0.348341    1  
2457               Dallas Mavericks - Utah Jazz      118:68  0.651659    0  
2458             Chicago Bulls - Boston Celtics      77:133  0.748031    1  
2459             Chicago Bulls - Boston Celtics      77:133  0.251969    0  

[2460 rows x 16 columns]

In [ ]:
# 2.	Calculate the implied win probability based on the bookmaker odds

In [23]:
# Calculate the implied win probability from the decimal odds

NBA19['winprob']= 1/(NBA19['winodds'])/(1/(NBA19['winodds'])+ 1/(NBA19['loseodds']))

In [ ]:
# 3.	Drop from the data all games for which home = 0

In [24]:
NBA19 = NBA19[NBA19.home == 1]
NBA19

team                opponent  day  month  year  \
0     Golden State Warriors         Houston Rockets    4      1  2019   
3        Washington Wizards         New York Knicks   17      1  2019   
4            Boston Celtics      Los Angeles Lakers    8      2  2019   
7          Dallas Mavericks  Portland Trail Blazers   10      2  2019   
11        Memphis Grizzlies       San Antonio Spurs   13      2  2019   
...                     ...                     ...  ...    ...   ...   
2450        Milwaukee Bucks  Portland Trail Blazers   22     11  2018   
2453         Denver Nuggets           Atlanta Hawks   16     11  2018   
2455  Golden State Warriors       Charlotte Hornets    1      4  2019   
2456       Dallas Mavericks               Utah Jazz   15     11  2018   
2459          Chicago Bulls          Boston Celtics    9     12  2018   

      winodds  loseodds  teampts  oppopts  diff  overtime  home  \
0        1.27      3.92      134      135     1         1     1   
3        1.32      3.52      101      100     1         0     1   
4        1.24      4.31      128      129     1         0     1   
7        2.30      1.65      102      101     1         0     1   
11       3.57      1.32      107      108     1         0     1   
...       ...       ...      ...      ...   ...       ...   ...   
2450     1.33      3.48      143      100    43         0     1   
2453     1.08      8.97      138       93    45         0     1   
2455     1.13      6.42      137       90    47         0     1   
2456     2.75      1.47      118       68    50         0     1   
2459     3.80      1.28       77      133    56         0     1   

                                Game(home-away)     HAscore  win prob  win  \
0       Golden State Warriors - Houston Rockets  134:135 ET  0.755299    0   
3          Washington Wizards - New York Knicks     101:100  0.727273    1   
4           Boston Celtics - Los Angeles Lakers     128:129  0.776577    0   
7     Dallas Mavericks - Portland Trail Blazers     102:101  0.417722    1   
11        Memphis Grizzlies - San Antonio Spurs     107:108  0.269939    0   
...                                         ...         ...       ...  ...   
2450   Milwaukee Bucks - Portland Trail Blazers     143:100  0.723493    1   
2453             Denver Nuggets - Atlanta Hawks      138:93  0.892537    1   
2455  Golden State Warriors - Charlotte Hornets      137:90  0.850331    1   
2456               Dallas Mavericks - Utah Jazz      118:68  0.348341    1   
2459             Chicago Bulls - Boston Celtics      77:133  0.251969    0   

       winprob  absdiff  
0     0.755299        1  
3     0.727273        1  
4     0.776577        1  
7     0.417722        1  
11    0.269939        1  
...        ...      ...  
2450  0.723493       43  
2453  0.892537       45  
2455  0.850331       47  
2456  0.348341       50  
2459  0.251969       56  

[1230 rows x 18 columns]

In [25]:
np.corrcoef(NBA19["winprob"], NBA19['win'])

array([[1.        , 0.39652887],
       [0.39652887, 1.        ]])

In [ ]:
# Q1: What is the correlation between the home team win probability and home team wins across the entire 2018/19 season? 
# A1: +0.397

In [ ]:
# 4.	Then create the following subsets 
#     a. One for games where the absolute value of the points difference is less than 9 and another for games where the points difference is greater than 9 (9 is the median points difference in the data) 
#     b. One for games that went to overtime, and one for games which finished in regulation time 
#     c. One for games played in calendar year 2018, one for games played in calendar year 2019 
#     d. One for each month in the data (October to April)

In [26]:
# a. One for games where the absolute value of the points difference is less than 9 and another for games where the points difference is greater than 9 (9 is the median points difference in the data) 
NBA19['absdiff'] = abs(NBA19['teampts'] - NBA19['oppopts']) 
NBA19

team                opponent  day  month  year  \
0     Golden State Warriors         Houston Rockets    4      1  2019   
3        Washington Wizards         New York Knicks   17      1  2019   
4            Boston Celtics      Los Angeles Lakers    8      2  2019   
7          Dallas Mavericks  Portland Trail Blazers   10      2  2019   
11        Memphis Grizzlies       San Antonio Spurs   13      2  2019   
...                     ...                     ...  ...    ...   ...   
2450        Milwaukee Bucks  Portland Trail Blazers   22     11  2018   
2453         Denver Nuggets           Atlanta Hawks   16     11  2018   
2455  Golden State Warriors       Charlotte Hornets    1      4  2019   
2456       Dallas Mavericks               Utah Jazz   15     11  2018   
2459          Chicago Bulls          Boston Celtics    9     12  2018   

      winodds  loseodds  teampts  oppopts  diff  overtime  home  \
0        1.27      3.92      134      135     1         1     1   
3        1.32      3.52      101      100     1         0     1   
4        1.24      4.31      128      129     1         0     1   
7        2.30      1.65      102      101     1         0     1   
11       3.57      1.32      107      108     1         0     1   
...       ...       ...      ...      ...   ...       ...   ...   
2450     1.33      3.48      143      100    43         0     1   
2453     1.08      8.97      138       93    45         0     1   
2455     1.13      6.42      137       90    47         0     1   
2456     2.75      1.47      118       68    50         0     1   
2459     3.80      1.28       77      133    56         0     1   

                                Game(home-away)     HAscore  win prob  win  \
0       Golden State Warriors - Houston Rockets  134:135 ET  0.755299    0   
3          Washington Wizards - New York Knicks     101:100  0.727273    1   
4           Boston Celtics - Los Angeles Lakers     128:129  0.776577    0   
7     Dallas Mavericks - Portland Trail Blazers     102:101  0.417722    1   
11        Memphis Grizzlies - San Antonio Spurs     107:108  0.269939    0   
...                                         ...         ...       ...  ...   
2450   Milwaukee Bucks - Portland Trail Blazers     143:100  0.723493    1   
2453             Denver Nuggets - Atlanta Hawks      138:93  0.892537    1   
2455  Golden State Warriors - Charlotte Hornets      137:90  0.850331    1   
2456               Dallas Mavericks - Utah Jazz      118:68  0.348341    1   
2459             Chicago Bulls - Boston Celtics      77:133  0.251969    0   

       winprob  absdiff  
0     0.755299        1  
3     0.727273        1  
4     0.776577        1  
7     0.417722        1  
11    0.269939        1  
...        ...      ...  
2450  0.723493       43  
2453  0.892537       45  
2455  0.850331       47  
2456  0.348341       50  
2459  0.251969       56  

[1230 rows x 18 columns]

In [27]:
np.median(NBA19['absdiff'])

9.0

In [28]:
NBAl = NBA19[NBA19['absdiff']<9]
np.corrcoef(NBAl["winprob"], NBAl['win'])

array([[1.        , 0.19811648],
       [0.19811648, 1.        ]])

In [ ]:
# Q2: What is the correlation between the home team win probability and home team wins for games where the points difference was less than 9?
# A2: +0.198

In [29]:
NBAh = NBA19[NBA19['absdiff']>9]
np.corrcoef(NBAh["winprob"], NBAh['win'])

array([[1.        , 0.57647206],
       [0.57647206, 1.        ]])

In [ ]:
# Q3: What is the correlation between the home team win probability and home team wins for games where the points difference was greater than 9?
# A3: +0.576

In [ ]:
# Q4: Considering the answers to the last two questions, what do you think is the most likely explanation of these results
# A4: Uncertain games are ones where the bookmakers odds are most likely to be wrong and the scores are likely to be closest

In [30]:
# b. One for games that went to overtime, and one for games which finished in regulation time
NBAOT = NBA19[NBA19['overtime'] == 1]
np.corrcoef(NBAOT["winprob"], NBAOT['win'])

array([[1.        , 0.03225853],
       [0.03225853, 1.        ]])

In [ ]:
# Q5: What is the correlation between the home team win probability and home team wins for games where the game went to overtime?
# A5: +0.032

In [31]:
NBAreg = NBA19[NBA19['overtime'] == 0]
np.corrcoef(NBAreg["winprob"], NBAreg['win'])

array([[1.       , 0.4144347],
       [0.4144347, 1.       ]])

In [ ]:
# Q6: What is the correlation between the home team win probability and home team wins for games where the game was finished in regular time?
# A6: +0.414

In [32]:
# c. One for games played in calendar year 2018, one for games played in calendar year 2019
NBA2018 = NBA19[NBA19['year'] == 2018]
np.corrcoef(NBA2018["winprob"], NBA2018['win'])

array([[1.        , 0.33824657],
       [0.33824657, 1.        ]])

In [ ]:
# Q7: What is the correlation between the home team win probability and home team wins for games where the game was played in calendar year 2018?
# A7: +0.338

In [33]:
NBA2019 = NBA19[NBA19['year'] == 2019]
np.corrcoef(NBA2019["winprob"], NBA2019['win'])

array([[1.        , 0.43797601],
       [0.43797601, 1.        ]])

In [ ]:
# Q8: What is the correlation between the home team win probability and home team wins for games where the game was played in calendar year 2019?
# A8: +0.438

In [16]:
# d. One for each month in the data (October to April)
NBAOct = NBA19[NBA19['month'] == 10]
np.corrcoef(NBAOct["winprob"], NBAOct['win'])

array([[1.       , 0.4132173],
       [0.4132173, 1.       ]])

In [17]:
NBANov = NBA19[NBA19['month'] == 11]
np.corrcoef(NBANov["winprob"], NBANov['win'])

array([[1.        , 0.31889017],
       [0.31889017, 1.        ]])

In [18]:
NBADec = NBA19[NBA19['month'] == 12]
np.corrcoef(NBADec["winprob"], NBADec['win'])

array([[1.        , 0.32183843],
       [0.32183843, 1.        ]])

In [19]:
NBAJan = NBA19[NBA19['month'] == 1]
np.corrcoef(NBAJan["winprob"], NBAJan['win'])

array([[1.       , 0.5035297],
       [0.5035297, 1.       ]])

In [20]:
NBAFeb = NBA19[NBA19['month'] == 2]
np.corrcoef(NBAFeb["winprob"], NBAFeb['win'])

array([[1.        , 0.37928007],
       [0.37928007, 1.        ]])

In [21]:
NBAMar = NBA19[NBA19['month'] == 3]
np.corrcoef(NBAMar["winprob"], NBAMar['win'])

array([[1.        , 0.41270836],
       [0.41270836, 1.        ]])

In [22]:
NBAApr = NBA19[NBA19['month'] == 4]
np.corrcoef(NBAApr["winprob"], NBAApr['win'])

array([[1.       , 0.4554355],
       [0.4554355, 1.       ]])

In [ ]:
# Q9: In which month was the correlation coefficient between the home team win probability and home team wins greatest?
# A9: Jan

In [ ]:
# Q10: In which month was the correlation coefficient between the home team win probability and home team wins lowest?
# A10: Nov